<a href="https://colab.research.google.com/github/Sylwiana/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PODSTAWY

In [1]:
import numpy as np
np.__version__

'1.25.2'

In [2]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

1D Array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

In [5]:
x.ndim

1

In [6]:
x.shape

(2,)

In [7]:
x.size

2

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [10]:
x.dtype

dtype('float64')

2D Array

In [11]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [12]:
x.ndim

2

In [13]:
x.shape

(2, 2)

In [14]:
y = np.array([[1,2,4], [4,2,1]])
print(y)

[[1 2 4]
 [4 2 1]]


In [15]:
y.shape

(2, 3)

3D Array

In [16]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [17]:
x.ndim

3

In [18]:
x.shape

(2, 2, 3)

In [19]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [20]:
x.shape

(3, 2, 3)

In [21]:
x.ndim

3

Typ danych

In [22]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [23]:
A =  np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [24]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [25]:
A = np.array([1,2,3],dtype='complex')
A.dtype

dtype('complex128')

In [26]:
A =  np.array([1.0, 2.5, 3.3], dtype='int')
A.dtype

dtype('int64')

In [27]:
A

array([1, 2, 3])

In [28]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [29]:
A =  np.array([1.0, 2.3, 3.3], dtype=np.int8)
A.dtype

dtype('int8')

Tworzenie tablic

In [30]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros(shape=(4, 10),dtype='int')


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [33]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [36]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
np.arange(start=0, stop=1, step=0.05 )

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [38]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [40]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [41]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [43]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [44]:
A+B

array([6, 0, 7, 4])

In [45]:
np.add(A, B) #metoda na dodawanie tablic

array([6, 0, 7, 4])

In [46]:
A-B

array([0, 2, 1, 0])

In [47]:
np.subtract(A, B) #metoda na odejmowanie tablic

array([0, 2, 1, 0])

In [48]:
A*B

array([ 9, -1, 12,  4])

In [49]:
np.multiply(A, B) # metoda na mnożenie tablic

array([ 9, -1, 12,  4])

In [50]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [51]:
np.divide(A, B) # metoda na dzielenie tablic

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [52]:
A + 3

array([6, 4, 7, 5])

In [53]:
4*B

array([12, -4, 12,  8])

In [54]:
X = np.array([[1, 3], [-2,0]])
Y = np.array([[6, 0 ], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [55]:
X*Y #niealgebraiczne mnożenie

array([[6, 0],
       [2, 0]])

MNOŻENIE MACIERZY

In [56]:
np.dot(X, Y) #MNOŻENE MACIERZY

array([[  3,   6],
       [-12,   0]])

In [57]:
X.dot(Y) # można też tak napisać

array([[  3,   6],
       [-12,   0]])

In [58]:
Y.dot(X) # tutaj mamy inny wynik,bo mnożenie macierzy nie jest naprzemienne!!!

array([[ 6, 18],
       [-5, -3]])

In [59]:
X @ Y # symbol add - tak też możemy zapisać mnożenie!!!

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych


In [60]:
np.random.seed(0) #ustalamy konkretne ziarno losowe

In [61]:
 np.random.randn()

1.764052345967664

In [62]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [63]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [64]:
np. random.rand()

0.1965823616800535

In [65]:
np.random.rand(10, 2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [66]:
np.random.randint(10)

1

In [67]:
np.random.randint(low=10, high=101,  size=10)

array([60, 37, 24, 51, 68, 75, 46, 20, 96, 53])

In [68]:
np.random.choice([4,5,6,7,8,9,2])

4

In [69]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [70]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.random.shuffle(data)
data

array([5, 1, 4, 2, 9, 7, 6, 8, 0, 3])

Podstawowe funkcje wbudowane

In [72]:
np.exp(1)

2.718281828459045

In [73]:
np.sqrt(9)

3.0

In [74]:
np.all([4,3,2,1])

True

In [75]:
np.any([9,3,0])

True

In [76]:
 bool(1.3)

True

In [77]:
A = np.random.rand(5)
A

array([0.02010755, 0.82894003, 0.00469548, 0.67781654, 0.27000797])

In [78]:
np.argmax(A) #zwraca indeks z  największą wartość

1

In [79]:
A[np.argmax(A)] #wycinamy sobie nasz index 1 z największą wartością

0.8289400292173631

In [80]:
np.argmin(A) # zwraca indeksc z najmniejszą wartością

2

In [81]:
np.argsort(A) # sortuje wartości i zwraca indeksy posortowanych wartości domyślnie rosnąco

array([2, 0, 4, 3, 1])

In [82]:
np.max(A) #zwraca największą wartość

0.8289400292173631

In [83]:
 np.min(A) #zwraca najmniejszą wartość

0.004695476192547066

In [84]:
np.mean(A) #zwraca średnią

0.36031351231715975

In [85]:
np.median(A) # zwraca medianę

0.27000797319216485

In [86]:
np.std(A) #zwraca odchylenie standardowe

0.33786931210140275

Indeksowanie, wycinanie

In [87]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
A[2]

2

In [89]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [90]:
A[:2]

array([0, 1])

In [91]:
A[[0,2]] #wycina tylko 0 i 2 indeks

array([0, 2])

In [92]:
A[10:15]

array([10, 11, 12, 13, 14])

In [93]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
A[0]# wycina cały pierwszy wiersz

array([0, 1, 2, 3, 4])

In [95]:
A[1]

array([5, 6, 7, 8, 9])

In [96]:
A[:,0] #wycinamy pierwszą kolumną z indeksem 0

array([ 0,  5, 10, 15])

In [97]:
A[:, -1] # wycinamy ostatnią kolumnę

array([ 4,  9, 14, 19])

In [98]:
A[:, -2] #wycinamy przedostatnią kolumnę

array([ 3,  8, 13, 18])

In [99]:
A[1:3, 1:4] # wycinamy jakiś fragment z przedziałów

array([[ 6,  7,  8],
       [11, 12, 13]])

In [100]:
A[1, 2]

7

In [101]:
A[1,2]=14 #przypisanie nowej wartości konkretnej wartości
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [102]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [104]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [105]:
for row in A:
  print(row[0])

0
5
10
15


In [106]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [107]:
 for item in A.flat: # iterowanie element po elemencie,po spłaszczeniu A przez atrybut flat
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [108]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
A.shape

(4, 5)

In [110]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [111]:
A .ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [112]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [114]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [115]:
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [116]:
A>0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [118]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [119]:
np.bitwise_and(A > -5, A < 5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [120]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])